### ISSUE TITLE
error 500: Agreements

### ISSUE THREAD

**Issue by RogierKentie** [MichMich/MMM-Toon#1]
I get this error:
`"{"code":500,"type":"Internal server error.","message":"Unable to find virtual display. Try to register the display first.","description":"Unable to find virtual display. Try to register the display first."}"`

Do you know what the problem can be? Total Noob, so have no idea and can't Google it.

**Comment by MichMich** [comment]
Which API keys did you use?

**Comment by RogierKentie** [comment]
The two you get when you make a Developer Account on toonapi.com. I guess it aren't the right ones.
