### ISSUE TITLE
can't get it work. 

### ISSUE THREAD

**Issue by sjoerdvanaken** [MichMich/MMM-Toon#9]
id did everything from the read m’n and try something to get it working. but the only thing I can see on the mm2 display is bezig met laden. and that's it.

**Comment by hypoflex** [comment]
have a look at my updated configuration which was made to support the latest version of Toon. @ https://github.com/MichMich/MMM-Toon/pull/8


----------------------------
the new version of the API doesn't require `username` or `password` instead can use a `Access token` which has to be obtained by the user through login in "Mijn Eneco".

First off you need your `API key`: https://developer.toon.eu/user/me/apps also known as `Consumer key`.
after obtaining the `API key` you can go and retreive your `Access Token`.

**Access token can be retrieved from in the browser, this requires you to login to "Mijn Eneco":**
https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<API_Key>
_this access key is valid for 10 years_

after that set the new config in your MMM

**New config:**
```
	{
	module: 'MMM-Toon',
	position: 'top_right', // This can be any of the regions.
		config: {
			apiKey: 'ABCDEFG', // Obtained from developer.toon.eu
			apiSecret: 'ABCDEFG', // Obtained from developer.toon.eu
			accessToken: "123456-123456-123456-123456", Obtained from the api
		}
	}
```

**Comment by nymeia** [comment]
I used your config but getting Electron errors:

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir | [27.01.2021 16:07.10.188] [ERROR] Whoops! There was an uncaught exception...
0|MagicMir | [27.01.2021 16:07.10.196] [ERROR] ReferenceError: NodeHelper is not defined
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Toon/node_helper.js:11:18)
0|MagicMir |     at Module._compile (internal/modules/cjs/loader.js:968:30)
0|MagicMir |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
0|MagicMir |     at Module.load (internal/modules/cjs/loader.js:816:32)
0|MagicMir |     at Module._load (internal/modules/cjs/loader.js:728:14)
0|MagicMir |     at Function.Module._load (electron/js2c/asar.js:748:26)
0|MagicMir |     at Module.require (internal/modules/cjs/loader.js:853:19)
0|MagicMir |     at require (internal/modules/cjs/helpers.js:74:18)
0|MagicMir |     at loadModule (/home/pi/MagicMirror/js/app.js:134:17)
0|MagicMir |     at loadNextModule (/home/pi/MagicMirror/js/app.js:169:5)
0|MagicMir | [27.01.2021 16:07.10.198] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMir | [27.01.2021 16:07.10.201] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|MagicMir | [27.01.2021 16:07.12.406] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
